name: 'Destroying Infrastructure'

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "destroy" to destroy it'
        required: true
        
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

jobs:
  cleanup_ecr:
    name: 'Cleanup ECR'
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.confirm == 'destroy'

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: List and delete ECR images
      env:
        ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
      run: |
        REPOSITORY_NAME="${ECR_REPOSITORY}"
        IMAGE_IDS=$(aws ecr list-images --repository-name $REPOSITORY_NAME --query 'imageIds[*]' --output json)
        if [ "$IMAGE_IDS" != "[]" ]; then
          aws ecr batch-delete-image --repository-name $REPOSITORY_NAME --image-ids "$IMAGE_IDS"
        fi

  terraform_destroy_eks:
    name: 'Destroy EKS'
    runs-on: ubuntu-latest
    needs: cleanup_ecr

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.8.2

    - name: Terraform Init EKS
      working-directory: ./EKS
      run: terraform init

    - name: Terraform Destroy EKS
      working-directory: ./EKS
      run: terraform destroy -auto-approve

  terraform_destroy_rds:
    name: 'Destroy RDS'
    runs-on: ubuntu-latest
    needs: terraform_destroy_eks

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.8.2

    - name: Terraform Init RDS
      working-directory: ./RDS
      run: terraform init

    - name: Terraform Destroy RDS
      working-directory: ./RDS
      run: terraform destroy -auto-approve
